/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advance {
  'workerId' : WorkerId,
  'date' : string,
  'note' : string,
  'amount' : bigint,
}
export interface Attendance {
  'workerId' : WorkerId,
  'date' : string,
  'morningPresent' : boolean,
  'afternoonPresent' : boolean,
}
export interface LaborRecord {
  'id' : LaborRecordId,
  'afternoonCount' : bigint,
  'dailyRate' : bigint,
  'ownerId' : OwnerId,
  'date' : string,
  'morningCount' : bigint,
  'totalAmount' : bigint,
  'category' : string,
}
export type LaborRecordId = bigint;
export interface Owner { 'id' : OwnerId, 'name' : string, 'site' : string }
export type OwnerId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyBalance {
  'ownerId' : OwnerId,
  'week' : string,
  'finalPayable' : bigint,
  'prevBalance' : bigint,
  'thisWeekTotal' : bigint,
  'advanceDeduction' : bigint,
}
export interface Worker {
  'id' : WorkerId,
  'active' : boolean,
  'dailyRate' : bigint,
  'name' : string,
  'site' : string,
  'mobile' : string,
}
export type WorkerId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdvance' : ActorMethod<[WorkerId, bigint, string, string], Advance>,
  'createAttendance' : ActorMethod<
    [WorkerId, string, boolean, boolean],
    Attendance
  >,
  'createLaborRecord' : ActorMethod<
    [OwnerId, string, string, bigint, bigint, bigint],
    LaborRecord
  >,
  'createOwner' : ActorMethod<[string, string], Owner>,
  'createSite' : ActorMethod<[string], undefined>,
  'createWeeklyBalance' : ActorMethod<
    [OwnerId, string, bigint, bigint, bigint],
    WeeklyBalance
  >,
  'createWorker' : ActorMethod<[string, string, string, bigint], Worker>,
  'deleteAdvance' : ActorMethod<[WorkerId, string], undefined>,
  'deleteAttendance' : ActorMethod<[WorkerId, string], undefined>,
  'deleteLaborRecord' : ActorMethod<[LaborRecordId], undefined>,
  'deleteOwner' : ActorMethod<[OwnerId], undefined>,
  'deleteSite' : ActorMethod<[string], undefined>,
  'deleteWorker' : ActorMethod<[WorkerId], undefined>,
  'getAdvancesByWorker' : ActorMethod<[WorkerId], Array<Advance>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<Attendance>>,
  'getAttendanceByWorker' : ActorMethod<[WorkerId], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<
    [],
    { 'totalPendingBalance' : bigint, 'activeWorkers' : bigint }
  >,
  'getLaborRecordsByOwner' : ActorMethod<[OwnerId], Array<LaborRecord>>,
  'getOwner' : ActorMethod<[OwnerId], [] | [Owner]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyBalance' : ActorMethod<[string], [] | [WeeklyBalance]>,
  'getWorker' : ActorMethod<[WorkerId], [] | [Worker]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listOwners' : ActorMethod<[], Array<Owner>>,
  'listSites' : ActorMethod<[], Array<string>>,
  'listWorkers' : ActorMethod<[], Array<Worker>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAttendance' : ActorMethod<
    [WorkerId, string, boolean, boolean],
    undefined
  >,
  'updateLaborRecord' : ActorMethod<
    [LaborRecordId, string, string, bigint, bigint, bigint],
    LaborRecord
  >,
  'updateOwner' : ActorMethod<[OwnerId, string, string], Owner>,
  'updateWeeklyBalance' : ActorMethod<
    [OwnerId, string, bigint, bigint, bigint],
    WeeklyBalance
  >,
  'updateWorker' : ActorMethod<
    [WorkerId, string, string, string, bigint, boolean],
    Worker
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];