/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkerId = IDL.Nat;
export const Advance = IDL.Record({
  'workerId' : WorkerId,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Attendance = IDL.Record({
  'workerId' : WorkerId,
  'date' : IDL.Text,
  'morningPresent' : IDL.Bool,
  'afternoonPresent' : IDL.Bool,
});
export const OwnerId = IDL.Nat;
export const LaborRecordId = IDL.Nat;
export const LaborRecord = IDL.Record({
  'id' : LaborRecordId,
  'afternoonCount' : IDL.Int,
  'dailyRate' : IDL.Nat,
  'ownerId' : OwnerId,
  'date' : IDL.Text,
  'morningCount' : IDL.Int,
  'totalAmount' : IDL.Int,
  'category' : IDL.Text,
});
export const Owner = IDL.Record({
  'id' : OwnerId,
  'name' : IDL.Text,
  'site' : IDL.Text,
});
export const WeeklyBalance = IDL.Record({
  'ownerId' : OwnerId,
  'week' : IDL.Text,
  'finalPayable' : IDL.Int,
  'prevBalance' : IDL.Int,
  'thisWeekTotal' : IDL.Int,
  'advanceDeduction' : IDL.Int,
});
export const Worker = IDL.Record({
  'id' : WorkerId,
  'active' : IDL.Bool,
  'dailyRate' : IDL.Nat,
  'name' : IDL.Text,
  'site' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdvance' : IDL.Func(
      [WorkerId, IDL.Nat, IDL.Text, IDL.Text],
      [Advance],
      [],
    ),
  'createAttendance' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Bool, IDL.Bool],
      [Attendance],
      [],
    ),
  'createLaborRecord' : IDL.Func(
      [OwnerId, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Nat],
      [LaborRecord],
      [],
    ),
  'createOwner' : IDL.Func([IDL.Text, IDL.Text], [Owner], []),
  'createSite' : IDL.Func([IDL.Text], [], []),
  'createWeeklyBalance' : IDL.Func(
      [OwnerId, IDL.Text, IDL.Int, IDL.Int, IDL.Int],
      [WeeklyBalance],
      [],
    ),
  'createWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Worker],
      [],
    ),
  'deleteAdvance' : IDL.Func([WorkerId, IDL.Text], [], []),
  'deleteAttendance' : IDL.Func([WorkerId, IDL.Text], [], []),
  'deleteLaborRecord' : IDL.Func([LaborRecordId], [], []),
  'deleteOwner' : IDL.Func([OwnerId], [], []),
  'deleteSite' : IDL.Func([IDL.Text], [], []),
  'deleteWorker' : IDL.Func([WorkerId], [], []),
  'getAdvancesByWorker' : IDL.Func([WorkerId], [IDL.Vec(Advance)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getAttendanceByWorker' : IDL.Func(
      [WorkerId],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPendingBalance' : IDL.Int,
          'activeWorkers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLaborRecordsByOwner' : IDL.Func(
      [OwnerId],
      [IDL.Vec(LaborRecord)],
      ['query'],
    ),
  'getOwner' : IDL.Func([OwnerId], [IDL.Opt(Owner)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyBalance' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WeeklyBalance)],
      ['query'],
    ),
  'getWorker' : IDL.Func([WorkerId], [IDL.Opt(Worker)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listOwners' : IDL.Func([], [IDL.Vec(Owner)], ['query']),
  'listSites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAttendance' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'updateLaborRecord' : IDL.Func(
      [LaborRecordId, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Nat],
      [LaborRecord],
      [],
    ),
  'updateOwner' : IDL.Func([OwnerId, IDL.Text, IDL.Text], [Owner], []),
  'updateWeeklyBalance' : IDL.Func(
      [OwnerId, IDL.Text, IDL.Int, IDL.Int, IDL.Int],
      [WeeklyBalance],
      [],
    ),
  'updateWorker' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [Worker],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkerId = IDL.Nat;
  const Advance = IDL.Record({
    'workerId' : WorkerId,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Attendance = IDL.Record({
    'workerId' : WorkerId,
    'date' : IDL.Text,
    'morningPresent' : IDL.Bool,
    'afternoonPresent' : IDL.Bool,
  });
  const OwnerId = IDL.Nat;
  const LaborRecordId = IDL.Nat;
  const LaborRecord = IDL.Record({
    'id' : LaborRecordId,
    'afternoonCount' : IDL.Int,
    'dailyRate' : IDL.Nat,
    'ownerId' : OwnerId,
    'date' : IDL.Text,
    'morningCount' : IDL.Int,
    'totalAmount' : IDL.Int,
    'category' : IDL.Text,
  });
  const Owner = IDL.Record({
    'id' : OwnerId,
    'name' : IDL.Text,
    'site' : IDL.Text,
  });
  const WeeklyBalance = IDL.Record({
    'ownerId' : OwnerId,
    'week' : IDL.Text,
    'finalPayable' : IDL.Int,
    'prevBalance' : IDL.Int,
    'thisWeekTotal' : IDL.Int,
    'advanceDeduction' : IDL.Int,
  });
  const Worker = IDL.Record({
    'id' : WorkerId,
    'active' : IDL.Bool,
    'dailyRate' : IDL.Nat,
    'name' : IDL.Text,
    'site' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdvance' : IDL.Func(
        [WorkerId, IDL.Nat, IDL.Text, IDL.Text],
        [Advance],
        [],
      ),
    'createAttendance' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Bool, IDL.Bool],
        [Attendance],
        [],
      ),
    'createLaborRecord' : IDL.Func(
        [OwnerId, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Nat],
        [LaborRecord],
        [],
      ),
    'createOwner' : IDL.Func([IDL.Text, IDL.Text], [Owner], []),
    'createSite' : IDL.Func([IDL.Text], [], []),
    'createWeeklyBalance' : IDL.Func(
        [OwnerId, IDL.Text, IDL.Int, IDL.Int, IDL.Int],
        [WeeklyBalance],
        [],
      ),
    'createWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Worker],
        [],
      ),
    'deleteAdvance' : IDL.Func([WorkerId, IDL.Text], [], []),
    'deleteAttendance' : IDL.Func([WorkerId, IDL.Text], [], []),
    'deleteLaborRecord' : IDL.Func([LaborRecordId], [], []),
    'deleteOwner' : IDL.Func([OwnerId], [], []),
    'deleteSite' : IDL.Func([IDL.Text], [], []),
    'deleteWorker' : IDL.Func([WorkerId], [], []),
    'getAdvancesByWorker' : IDL.Func([WorkerId], [IDL.Vec(Advance)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceByWorker' : IDL.Func(
        [WorkerId],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPendingBalance' : IDL.Int,
            'activeWorkers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLaborRecordsByOwner' : IDL.Func(
        [OwnerId],
        [IDL.Vec(LaborRecord)],
        ['query'],
      ),
    'getOwner' : IDL.Func([OwnerId], [IDL.Opt(Owner)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WeeklyBalance)],
        ['query'],
      ),
    'getWorker' : IDL.Func([WorkerId], [IDL.Opt(Worker)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listOwners' : IDL.Func([], [IDL.Vec(Owner)], ['query']),
    'listSites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAttendance' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updateLaborRecord' : IDL.Func(
        [LaborRecordId, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Nat],
        [LaborRecord],
        [],
      ),
    'updateOwner' : IDL.Func([OwnerId, IDL.Text, IDL.Text], [Owner], []),
    'updateWeeklyBalance' : IDL.Func(
        [OwnerId, IDL.Text, IDL.Int, IDL.Int, IDL.Int],
        [WeeklyBalance],
        [],
      ),
    'updateWorker' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [Worker],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };