/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type LaborRecordId = bigint;
export interface WeeklyBalance {
    ownerId: OwnerId;
    week: string;
    finalPayable: bigint;
    prevBalance: bigint;
    thisWeekTotal: bigint;
    advanceDeduction: bigint;
}
export interface LaborRecord {
    id: LaborRecordId;
    afternoonCount: bigint;
    dailyRate: bigint;
    ownerId: OwnerId;
    date: string;
    morningCount: bigint;
    totalAmount: bigint;
    category: string;
}
export interface Advance {
    workerId: WorkerId;
    date: string;
    note: string;
    amount: bigint;
}
export interface Attendance {
    workerId: WorkerId;
    date: string;
    morningPresent: boolean;
    afternoonPresent: boolean;
}
export type WorkerId = bigint;
export interface Owner {
    id: OwnerId;
    name: string;
    site: string;
}
export interface Worker {
    id: WorkerId;
    active: boolean;
    dailyRate: bigint;
    name: string;
    site: string;
    mobile: string;
}
export interface UserProfile {
    name: string;
}
export type OwnerId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAdvance(workerId: WorkerId, amount: bigint, date: string, note: string): Promise<Advance>;
    createAttendance(workerId: WorkerId, date: string, morningPresent: boolean, afternoonPresent: boolean): Promise<Attendance>;
    createLaborRecord(ownerId: OwnerId, category: string, date: string, morningCount: bigint, afternoonCount: bigint, dailyRate: bigint): Promise<LaborRecord>;
    createOwner(name: string, site: string): Promise<Owner>;
    createSite(site: string): Promise<void>;
    createWeeklyBalance(ownerId: OwnerId, week: string, prevBalance: bigint, advanceDeduction: bigint, thisWeekTotal: bigint): Promise<WeeklyBalance>;
    createWorker(name: string, mobile: string, site: string, dailyRate: bigint): Promise<Worker>;
    deleteAdvance(workerId: WorkerId, date: string): Promise<void>;
    deleteAttendance(workerId: WorkerId, date: string): Promise<void>;
    deleteLaborRecord(id: LaborRecordId): Promise<void>;
    deleteOwner(id: OwnerId): Promise<void>;
    deleteSite(site: string): Promise<void>;
    deleteWorker(id: WorkerId): Promise<void>;
    getAdvancesByWorker(workerId: WorkerId): Promise<Array<Advance>>;
    getAttendanceByDate(date: string): Promise<Array<Attendance>>;
    getAttendanceByWorker(workerId: WorkerId): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboard(): Promise<{
        totalPendingBalance: bigint;
        activeWorkers: bigint;
    }>;
    getLaborRecordsByOwner(ownerId: OwnerId): Promise<Array<LaborRecord>>;
    getOwner(id: OwnerId): Promise<Owner | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyBalance(week: string): Promise<WeeklyBalance | null>;
    getWorker(id: WorkerId): Promise<Worker | null>;
    isCallerAdmin(): Promise<boolean>;
    listOwners(): Promise<Array<Owner>>;
    listSites(): Promise<Array<string>>;
    listWorkers(): Promise<Array<Worker>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAttendance(workerId: WorkerId, date: string, morningPresent: boolean, afternoonPresent: boolean): Promise<void>;
    updateLaborRecord(id: LaborRecordId, category: string, date: string, morningCount: bigint, afternoonCount: bigint, dailyRate: bigint): Promise<LaborRecord>;
    updateOwner(id: OwnerId, name: string, site: string): Promise<Owner>;
    updateWeeklyBalance(ownerId: OwnerId, week: string, prevBalance: bigint, advanceDeduction: bigint, thisWeekTotal: bigint): Promise<WeeklyBalance>;
    updateWorker(id: WorkerId, name: string, mobile: string, site: string, dailyRate: bigint, active: boolean): Promise<Worker>;
}
import type { Owner as _Owner, UserProfile as _UserProfile, UserRole as _UserRole, WeeklyBalance as _WeeklyBalance, Worker as _Worker } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAdvance(arg0: WorkerId, arg1: bigint, arg2: string, arg3: string): Promise<Advance> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdvance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdvance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createAttendance(arg0: WorkerId, arg1: string, arg2: boolean, arg3: boolean): Promise<Attendance> {
        if (this.processError) {
            try {
                const result = await this.actor.createAttendance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAttendance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createLaborRecord(arg0: OwnerId, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint): Promise<LaborRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createLaborRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLaborRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createOwner(arg0: string, arg1: string): Promise<Owner> {
        if (this.processError) {
            try {
                const result = await this.actor.createOwner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOwner(arg0, arg1);
            return result;
        }
    }
    async createSite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSite(arg0);
            return result;
        }
    }
    async createWeeklyBalance(arg0: OwnerId, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<WeeklyBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.createWeeklyBalance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWeeklyBalance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createWorker(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<Worker> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorker(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorker(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAdvance(arg0: WorkerId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdvance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdvance(arg0, arg1);
            return result;
        }
    }
    async deleteAttendance(arg0: WorkerId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttendance(arg0, arg1);
            return result;
        }
    }
    async deleteLaborRecord(arg0: LaborRecordId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLaborRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLaborRecord(arg0);
            return result;
        }
    }
    async deleteOwner(arg0: OwnerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOwner(arg0);
            return result;
        }
    }
    async deleteSite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSite(arg0);
            return result;
        }
    }
    async deleteWorker(arg0: WorkerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorker(arg0);
            return result;
        }
    }
    async getAdvancesByWorker(arg0: WorkerId): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesByWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesByWorker(arg0);
            return result;
        }
    }
    async getAttendanceByDate(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0);
            return result;
        }
    }
    async getAttendanceByWorker(arg0: WorkerId): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByWorker(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<{
        totalPendingBalance: bigint;
        activeWorkers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return result;
        }
    }
    async getLaborRecordsByOwner(arg0: OwnerId): Promise<Array<LaborRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaborRecordsByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaborRecordsByOwner(arg0);
            return result;
        }
    }
    async getOwner(arg0: OwnerId): Promise<Owner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwner(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwner(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyBalance(arg0: string): Promise<WeeklyBalance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyBalance(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyBalance(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorker(arg0: WorkerId): Promise<Worker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorker(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorker(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listOwners(): Promise<Array<Owner>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOwners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOwners();
            return result;
        }
    }
    async listSites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSites();
            return result;
        }
    }
    async listWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkers();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAttendance(arg0: WorkerId, arg1: string, arg2: boolean, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLaborRecord(arg0: LaborRecordId, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint): Promise<LaborRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLaborRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLaborRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateOwner(arg0: OwnerId, arg1: string, arg2: string): Promise<Owner> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOwner(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOwner(arg0, arg1, arg2);
            return result;
        }
    }
    async updateWeeklyBalance(arg0: OwnerId, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<WeeklyBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeeklyBalance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeeklyBalance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateWorker(arg0: WorkerId, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: boolean): Promise<Worker> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorker(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorker(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Owner]): Owner | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeeklyBalance]): WeeklyBalance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Worker]): Worker | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
